# !/usr/bin/env python3
from django.core.management.base import BaseCommand, CommandError
from services.models import Geonames, ScheduledWork, PENDING, INPROGRESS, FINALIZED, ERROR, \
    SCHEDULED_WORK_CORRESPONDENCE_PROCESS
from datetime import datetime
from django.core.management import call_command
from django.utils import timezone

__author__ = 'Amaia Nazabal'


class Command(BaseCommand):
    help = ''

    def handle(self, *args, **options):

        self.stdout.write(
            self.style.MIGRATE_LABEL('%s : The process begins.' %
                                         (datetime.now())))
        scheduled_work = ScheduledWork.objects.get(name=SCHEDULED_WORK_CORRESPONDENCE_PROCESS, status=PENDING)

        try:
            geonames_entities = Geonames.objects.only('id').filter(correspondence_check=False).values()

            total_rows = len(geonames_entities)

            '''
            On garde le processus dans la table avec l'Ã©tat PENDING
            '''
            scheduled_work.status = INPROGRESS
            scheduled_work.total_rows = total_rows
            scheduled_work.initial_date = timezone.now()
            scheduled_work.save()

            for geonames_entity in geonames_entities:
                geonames_entity_id = geonames_entity['id']

                try:
                    call_command('correspondance', geonames_entity_id)

                    scheduled_work.affected_rows += 1
                    scheduled_work.save()

                except Exception as error:
                    scheduled_work.error_rows += 1
                    scheduled_work.save()
                    raise CommandError('%s Error: %s.Entity id %s' %
                                       (datetime.now(), str(error), geonames_entity_id))

            if scheduled_work.error_rows == scheduled_work.affected_rows:
                scheduled_work.status = ERROR
            else:
                scheduled_work.status = FINALIZED

            scheduled_work.final_date = timezone.now()
            scheduled_work.save()

            process_time = scheduled_work.final_date - scheduled_work.initial_date
            self.stdout.write('%s : The process %s ended in %s seconds with %d affected rows and %d '
                              'error rows. Total rows expected %d.' % (datetime.now(), scheduled_work.name,
                                                                       process_time,
                                                                       scheduled_work.affected_rows,
                                                                       scheduled_work.error_rows,
                                                                       scheduled_work.total_rows))
        except Exception as error:
            scheduled_work.status = ERROR
            scheduled_work.final_date = timezone.now()
            scheduled_work.save()

            raise CommandError(error)
